config/routes.rb
Rfeeder::Application.routes.draw do
  namespace 'api' do
    namespace 'v1' do
      resources :stories, only: [:show, :index, :update]
      resources :feeds
    end
  end
  resources :docs, only: [:index], path: '/api/swagger'
  get '/auth/openidconnect/callback', to: 'callback#index'
end

app/models/feed.rb
# == Schema Information
#
# Table name: feeds
#
#  id              :integer          not null, primary key
#  name            :string(255)      not null
#  url             :text             not null
#  last_fetched_at :datetime
#  feed_status_id  :integer          not null
#  created_at      :datetime
#  updated_at      :datetime
#

class Feed < ActiveRecord::Base
  has_many :stories, :dependent => :destroy
  belongs_to :status, :class_name => 'FeedStatus', :foreign_key => 'feed_status_id'

  def latest_entry_id
    stories.last.try(:entry_id)
  end

  def last_modified!(_last_modified)
    self.last_fetched_at=_last_modified
    save!
  end

  def status!(status_name)

  end
end

app/controllers/api/v1/feeds_controller.rb
module Api
  module V1
    class FeedsController < ApiController
      jsonapi resource: ::FeedResource

      def index

        scope=jsonapi_scope(Feed)
        so=scope.object
        scope.resolve #(fire the requests)
        render_jsonapi(scope, scope: false,
                       meta: {
                         page: {
                           total: so.total_pages,
                           current: so.current_page,
                           next: so.next_page,
                           prev: so.prev_page,
                           last: so.last_page?,
                           out_of_range: so.out_of_range?
                         },
                         count:  so.total_count
                       }
                      )
      end


      def update
        feed, success = jsonapi_update.to_a
        if success
          render_jsonapi(feed, scope: false)
        else
          render_errors_for(feed)
        end
      end

      def create
        feed, success = jsonapi_create.to_a

        if success
          render_jsonapi(feed, scope: false)
        else
          render_errors_for(feed)
        end
      end

      def destroy
        feed, success = jsonapi_destroy.to_a

        if success
          render json: { meta: {} }
        else
          render_errors_for(feed)
        end
      end
      # def show
      #   scope = jsonapi_scope(Story.where(id: params[:id]))
      #   render_jsonapi(scope.resolve.first, scope: false)
      # end

    end

  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.order('name').all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new(:status => FeedStatus.find(1))
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    @feed.status=FeedStatus.find(1)
    @feed.last_fetched_at=1.day.ago

    respond_to do |format|
      if @feed.save
        format.html { redirect_to feeds_path, notice: 'Feed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feed }
      else
        format.html { render action: 'new' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to feeds_path, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :url, :timestamp, :feed_status_id)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div>
    <%= @feed.last_fetched_at %>
  </div>
  <div>
    <%= @feed.status.name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Timestamp</th>
      <th>Feed status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.url %></td>
        <td><%= feed.last_fetched_at %></td>
        <td><%= feed.status.name %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>