config/routes.rb
Rfeeder::Application.routes.draw do
  namespace 'api' do
    namespace 'v1' do
      resources :stories, only: [:show, :index, :update]
      resources :feeds
    end
  end
  resources :docs, only: [:index], path: '/api/swagger'
  get '/auth/openidconnect/callback', to: 'callback#index'
end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id          :integer          not null, primary key
#  title       :text
#  permalink   :text
#  body        :text
#  entry_id    :text
#  feed_id     :integer          not null
#  published   :datetime
#  is_read     :boolean          default(FALSE), not null
#  is_starred  :boolean          default(FALSE), not null
#  keep_unread :boolean          default(FALSE)
#  created_at  :datetime
#  updated_at  :datetime
#

class Story < ActiveRecord::Base
  belongs_to :feed
  has_many :user_opens
  validates_uniqueness_of :entry_id, :scope => :feed_id

  attr_accessor :user_open

  scope :base, lambda { |the_user|
    includes(:feed)
    .select('stories.*, user_opens.last_opened_at as last_opened_at, user_opens.read_later_at as read_later_at')
    .order("id desc")
    .left_outer_joins(:user_opens)
    .where(["user_opens.user_id=? or user_opens.user_id is null",the_user.id])
  }
  def self.create_from_raw(feed, entry)
    #might fail!
    Story.create(:feed => feed,
                 :title => entry.title,
                 :permalink => entry.url,
                 :raw_body => entry,
                 :is_read => false,
                 :is_starred => false,
                 :published => entry.published || Time.now,
                 :entry_id => entry.id)

  end

  scope :filter, lambda { |filter, user|
    if filter.read_later? || filter.unread?
      sc=joins("LEFT JOIN user_opens ON stories.id=user_opens.story_id").where(["user_opens.user_id=?", user.id])

      if filter.read_later?
        sc=sc.where("user_opens.read_later_at is not null")
      end
      if filter.unread?
        sc=sc.where("user_opens.last_opened_at is null")
      end
      sc
    end
  }

  def headline
    self.title.nil? ? UNTITLED : strip_html(self.title)[0, 100]
  end

  def lead
    strip_html(self.body)[0, 600]
  end

  def source
    self.feed.name
  end

  def pretty_date
    I18n.l(self.published)
  end

  def seen_text
    user_open.opened? ? I18n.l(user_open.last_opened_at) : 'new'
  end

  def raw_body=(entry)
    self.body=extract_content(entry)
  end

  private


  #perhaps move this to an extractor
  def extract_content(entry)
    sanitized_content = ""

    if entry.content
      sanitized_content = sanitize(entry.content)
    elsif entry.summary
      sanitized_content = sanitize(entry.summary)
    end

    expand_absolute_urls(sanitized_content, entry.url)
  end

  def sanitize(content)
    Loofah.fragment(content.gsub(/<wbr>/i, "")).scrub!(:prune).to_s
  end

  def expand_absolute_urls(content, base_url)
    doc = Nokogiri::HTML.fragment(content)
    abs_re = URI::DEFAULT_PARSER.regexp[:ABS_URI]

    [["a", "href"], ["img", "src"], ["video", "src"]].each do |tag, attr|
      doc.css("#{tag}[#{attr}]").each do |node|
        url = node.get_attribute(attr)
        unless url =~ abs_re
          node.set_attribute(attr, URI.join(base_url, url).to_s)
        end
      end
    end

    doc.to_html
  end

  def strip_html(contents)
    Loofah.fragment(contents).text
  end
end

app/controllers/api/v1/stories_controller.rb
module Api
  module V1
    class StoriesController < ApiController
      #before_action :authenticate!

      jsonapi resource: ::StoryResource

      def index
        scope=jsonapi_scope(Story
               .base(the_user).limit(10))

        so=scope.object
        #scope.resolve #(fire the requests)
        render_jsonapi(scope, #scope: false,
                       meta: {
                         page: {
                           total: so.total_pages,
                           current: so.current_page,
                           next: so.next_page,
                           prev: so.prev_page,
                           last: so.last_page?,
                           out_of_range: so.out_of_range?
                         },
                         count:  so.total_count
                       }
                      )
      end


      def update
        story, success = jsonapi_update.to_a

        if success
          render_jsonapi(story, scope: false)
        else
          render_errors_for(story)
        end
      end

      # def show
      #   scope = jsonapi_scope(Story.where(id: params[:id]))
      #   render_jsonapi(scope.resolve.first, scope: false)
      # end




    end

  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, :only => [:show, :open, :mark_read, :mark_read_later]

  # GET /stories
  # GET /stories.json
  # params page,
  def index
    logger.debug(params[:q].inspect)
    @q=StoryFilter.new(params[:q])

    @stories = Story.includes(:feed).order('published DESC').filter(@q, current_user).page(params[:page])

    user_opens=UserOpen.for_stories(@stories, current_user).index_by(&:story_id)
    @stories.each do |story|
      story.user_open=user_opens[story.id] || UserOpen.missing(story, current_user)
    end
    render :partial => 'index' if params[:partial]
  end

  #POST /stories/mark_all_read
  #mark all stories read by me that are currently in the system
  #TODO: in a special selection
  def mark_all_read
    #TODO: this should be a background job:
    now=(params[:before] ? Time.parse(params[:before]) : Time.now)

    Story.joins('LEFT OUTER JOIN user_opens ON stories.id = user_opens.story_id').where(['(user_opens.id is null OR user_opens.last_opened_at is NULL ) AND stories.created_at<?', now]).find_each do |story|
      UserOpen.story_of_user(story, current_user).open!
    end

    render :json => {:status => 'ok'}
  end

  #POST /stories/1/mark_read
  def mark_read
    opened=UserOpen.story_of_user(@story, current_user)
    if params[:toggle]
      opened.toggle_open!
    else
      opened.open!
    end

    render :json => {:opened => opened.opened?}
  end

  def mark_read_later
    opened=UserOpen.story_of_user(@story, current_user)
    if params[:toggle]
      opened.toggle_read_later!
    else
      opened.read_later!
    end

    render :json => {:read_later => opened.read_later?}
  end


  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  def open
    UserOpen.story_of_user(@story, current_user).open!
    redirect_to @story.permalink
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_story
    @story = Story.find(params[:id])
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_index.html.erb
<% @stories.each do |story| %>
  <div>
    <h3>
      <%= link_to mark_read_story_path(story),
                  :class => 'js-new-story-indicator', :id => "new-story-#{story.id }", :remote => true,
                  :method => 'post' do %>
        <span class="read-story glyphicon glyphicon-ok-circle <%= 'storyNotRead' unless story.user_open.opened? %>"></span>
      <% end %>
      <%= link_to mark_read_later_story_path(story),
                  :class => 'js-read-later-story-indicator', :id => "read-later-story-#{story.id }", :remote => true,
                  :method => 'post' do %>
        <span class="read-later glyphicon glyphicon-bookmark <%= 'storyNotReadLater' unless story.user_open.read_later? %>"></span>
      <% end %>
      <%= story.feed.name %> :
      <%= link_to story.title, open_story_path(story), :target => 'rfeeder_target', :class => "js-open-story", "data-new-story-id" => story.id %>

    </h3>

    <div>
      <%= story.lead.html_safe %>
    </div>
    <div>
      <%= story.seen_text %> |
      <%= story.published %> |
      <%= story.entry_id %> |
      <%= story.created_at.iso8601 %>
    </div>
  </div>
<% end %>

<%= link_to_next_page @stories, 'More', :params => {:partial => true, :q => @q.to_hash}, :remote => true, :class => "js-next-storries-link next-storries-link btn btn-default" %>

app/views/stories/index.html.erb
<%= content_for :header do %>
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group btn-group">
      <%= link_to mark_all_read_stories_path(:before => Time.now.iso8601), :class => "btn btn-default js-mark-all-read", :remote => true, :method => :post do %>
        <span class="glyphicon glyphicon-ok-sign"></span>
      <% end %>
      <%= link_to root_path, :class => "btn btn-default js-mark-all-read" do %>
        <span class="glyphicon glyphicon-repeat"></span>
      <% end %>
    </div>
    <div class="btn-group btn-group-xs">
      <%= form_for :q, :remote => true, :method => :get, :html => {:class => "form-inline", :id => "js-search-filters", :role => "search"} do |f| %>
        <span class="form-group">
          <label style="color: #ffffff">
            <%= f.check_box :read_later, :class => "js-filter" %> later
          </label>
        </span>
        <span class="form-group">
          <label style="color: #ffffff" >
            <%= f.check_box :unread, :class => "js-filter" %> unread
          </label>
        </span>
        <%= hidden_field_tag "partial", "true" %>
      <% end %>
    </div>
  </div>
<% end %>

<div id="stories">
  <%= render :partial => 'index' %>
</div>

<%= content_for(:javascript) do %>

  Rfeeder.wire_mark_all_read();
  Rfeeder.wire_open_story();
  Rfeeder.wire_mark_read();
  Rfeeder.wire_mark_read_later();
  Rfeeder.wire_endless_scroll();
  Rfeeder.wire_search();

<% end %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Last modified:</strong>
  <%= @feed.last_fetched_at %>
</p>

<p>
  <strong>Feed status:</strong>
  <%= @feed.feed_status_id %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>